services:
  swft:
    build: .
    container_name: swft
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - swft_data:/app/data
      - /etc/localtime:/etc/localtime:ro
    networks:
      - proxy_network
      - storage_network
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: "1"
networks:
  proxy_network:
    external: true
  storage_network:
    external: true
volumes:
  swft_data:
    external: true
